// contain namespace of socket 
module.exports = {
  COMMUNITY_CHAT: "COMMUNITY_CHAT",
  USER_CONNECTED: "USER_CONNECTED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  TYPING: "TYPING",
  VERIFY_USER: "VERIFY_USER",
  LOGOUT: "LOGOUT",
  PRIVATE_CHAT: "PRIVATE_CHAT", // creating new chat event
  NEW_CHAT_USER: "NEW_CHAT_USER",
  ADD_USER_TO_CHAT: "ADD_USER_TO_CHAT", // add user to an active chat || create group chat,
  ACTIVE_CHAT: "ACTIVE_CHAT",
  LOG_IN: "LOG_IN",
  SIGN_UP: "SIGN_UP"
}